//Dependencies
import type { NextPage } from "next";
import Head from "next/head";

//Components
import Navbar from "@components/Navbar";
import Hero from "@components/Hero";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rafael Araujo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logotype.ico" />
      </Head>

      <Navbar />

      <Hero />
    </>
  );
};

export default Home;
