//Dependencies
import type { NextPage } from "next";
import Head from "next/head";

import { useLanguageState } from "@context/language";
import { useThemeState } from "@context/theme";

import colors from "@styles/colors.json";

//Components
import Navbar from "@components/Navbar";
import Hero from "@components/Hero";
import Projects from "@components/Projects";
import Footer from "@components/Footer";

interface Properties {
  [key: string]: {
    navbar: Array<{ name: string; link: string }>;
    hero: { title: string; description: string };
    projects?: Array<{
      thumbnail?: { photo?: string; video?: string };
      title?: string;
      description?: string;
      technologies?: Array<{ name?: string; link?: string }>;
      links?: Array<{ text?: string; link?: string }>;
    }>;
    footer?: Array<{ name?: string; link?: string }>;
  };
}

import data from "./data.json";

const props: Properties = data;

const Home: NextPage = () => {
  const [language, setLanguage] = useLanguageState();
  const [theme, setTheme] = useThemeState();

  return (
    <>
      <Head>
        <title>Rafael Araujo</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="theme-color"
          content={theme == "Light" ? colors.neutral100 : colors.neutral800}
        />
        <link rel="icon" href="/logotype.ico" />
        <link rel="apple-touch-icon" sizes="57x57" href="/logotype.ico" />
      </Head>

      <Navbar props={props[language].navbar} />

      <Hero props={props[language].hero} />

      <main>
        <Projects props={props[language].projects} />
      </main>

      <Footer props={props[language].footer} />
    </>
  );
};

export default Home;

// Footer -> OKAY
// Projects ->
// Hero ->
